{
 "title": "Jenkins: Performance and Health Overview",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage, Jenkins Job Status, and lot more.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "处理速率（webhook、Uptime）",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(max(jenkins_node_builds_count{node=\"master\"}) - (ceil(max((default_jenkins_uptime / 1000 / 60 / 2 ))) + ceil(max((default_jenkins_uptime / 1000 / 60 / 15 ))))) /max((default_jenkins_uptime / 1000 / 60 ))"
    }
   ]
  },
  {
   "title": "健康状态",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_health_check_score" }
   ]
  },
  {
   "title": "正常运行时间",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "default_jenkins_uptime" }
   ]
  },
  {
   "title": "平均每天构建数（Uptime、项目）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(max(jenkins_node_builds_count{node=\"master\"}) - (ceil(max((default_jenkins_uptime / 1000 / 60 / 2 ))) + ceil(max((default_jenkins_uptime / 1000 / 60 / 15 )))) + ceil(max((default_jenkins_uptime / 1000 / 60 / 60 / 24)))) / max((default_jenkins_uptime / 1000 / 60 / 60 / 24))"
    }
   ]
  },
  {
   "title": "内存占用",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "vm_memory_total_used" }
   ]
  },
  {
   "title": "Node 149 内存",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{hostip=~\"192.168.5.149\"} / (node_memory_MemTotal_bytes{hostip=~\"192.168.5.149\"})))* 100"
    }
   ]
  },
  {
   "title": "Node 149 磁盘",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{hostip=~\"192.168.5.149\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {hostip=~\"192.168.5.149\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "CPU 负载",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "vm_cpu_load" }
   ]
  },
  {
   "title": "24小时构建数（Uptime、项目）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(jenkins_node_builds_count{node=\"master\"}[1d])) - ( 1440 / 2 + 1440 / 15 + 1440 / 60 / 24)"
    }
   ]
  },
  {
   "title": "Node 150 内存",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{hostip=~\"192.168.5.150\"} / (node_memory_MemTotal_bytes{hostip=~\"192.168.5.150\"})))* 100"
    }
   ]
  },
  {
   "title": "Node 150 磁盘",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{hostip=~\"192.168.5.150\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {hostip=~\"192.168.5.150\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "执行器在用数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(default_jenkins_executors_busy)"
    }
   ]
  },
  {
   "title": "项目数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_project_count_value" }
   ]
  },
  {
   "title": "插件数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_plugins_active + jenkins_plugins_inactive"
    }
   ]
  },
  {
   "title": "可更新插件数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_withUpdate" }
   ]
  },
  {
   "title": "JVM 空闲率",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vm_memory_total_max - vm_memory_total_used) / vm_memory_total_max * 100.0"
    }
   ]
  },
  {
   "title": "处理速率（Uptime）",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " max(jenkins_node_builds_count{node=\"master\"}) /max((default_jenkins_uptime / 1000 / 60))"
    }
   ]
  },
  {
   "title": "Node 151 内存",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{hostip=~\"192.168.5.151\"} / (node_memory_MemTotal_bytes{hostip=~\"192.168.5.151\"})))* 100"
    }
   ]
  },
  {
   "title": "Node 151 磁盘",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{hostip=~\"192.168.5.151\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {hostip=~\"192.168.5.151\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "所有任务数（Uptime）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_node_builds_count{node=\"master\"}"
    }
   ]
  },
  {
   "title": "成功任务数（Uptime）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_success_total" }
   ]
  },
  {
   "title": "失败任务数（Uptime）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_failure_total" }
   ]
  },
  {
   "title": "取消任务（Uptime）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_aborted_total" }
   ]
  },
  {
   "title": "不稳定任务（Uptime）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_unstable_total" }
   ]
  },
  {
   "title": "任务队列",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  },
  {
   "title": "任务排队时长",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_queuing_duration" }
   ]
  },
  {
   "title": "处理速率（实时）",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count[10m])"
    }
   ]
  },
  {
   "title": "任务排队速率",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count[10m])"
    }
   ]
  },
  {
   "title": "任务执行时长",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_duration_milliseconds"
    }
   ]
  },
  {
   "title": "执行器健康",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(jenkins_job_building_duration)/sum(jenkins_job_building_duration_count))"
    }
   ]
  }
 ]
}