SELECT SUM(LO_EXTENDEDPRICE*LO_DISCOUNT) AS REVENUE
FROM ssb.lineorder , ssb.dates  
WHERE LO_ORDERDATE = D_DATEKEY
  AND D_YEARMONTHNUM = 199401
  AND LO_DISCOUNT BETWEEN 4 AND 6
  AND LO_QUANTITY BETWEEN 26 AND 35;